<?php
/**
 * Functions to handle theme customizer
 *
 * WARNING: This file is part of the core PrimaThemes framework.
 * DO NOT edit this file under any circumstances. 
 *
 * @category   PrimaThemes
 * @package    Framework
 * @subpackage Functions
 * @author     PrimaThemes
 * @link       http://www.primathemes.com
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Define Design Settings options.
 *
 * @since PrimaThemes 2.0
 */
function prima_design_settings() {
	if ( !current_theme_supports('prima-design-settings') ) 
		return false;
		
	$settings = array();
	return apply_filters( 'prima_design_settings_args', $settings );
}

/**
 * Define Design Settings default options.
 *
 * @since PrimaThemes 2.0
 */
function prima_design_settings_default() {
	if ( !current_theme_supports('prima-design-settings') ) 
		return false;
		
	$settings = prima_design_settings();
	if ( false === $settings ) return false;
	
	$defaut_settings = array();
	foreach ($settings as $setting) {
		if (isset($setting['id'])) 
			$defaut_settings[$setting['id']] = isset($setting['default']) ? $setting['default'] : '';
	}
	
	return $defaut_settings;
}

/**
 * Customize default theme customizer position.
 *
 * Default priority
 * title_tagline		- 20
 * colors				- 40
 * header_image 		- 60
 * background_image 	- 80
 * nav 					- 100
 * static_front_page 	- 120
 *
 * @since PrimaThemes 2.0
 */
add_action( 'customize_register', 'prima_design_settings_customize' );
function prima_design_settings_customize( $wp_customize ) {
	if ( !current_theme_supports('prima-design-settings') ) 
		return;
	
	/* Move "colors" section after "static_front_page" section */
	$wp_customize->get_section( 'colors' )->priority = 130;
	/* Rename "colors" section title to "Colors and Typography" */
	$wp_customize->get_section( 'colors' )->title = __( 'Colors & Typography', 'primathemes' );
	
	/* Move "background_image" section after "colors" section */
	$wp_customize->get_section( 'background_image' )->priority = 140;
	/* Rename "background_image" section title to "Background" */
	$wp_customize->get_section( 'background_image' )->title = __( 'Background', 'primathemes' );
	/* Move "background_color" control to "background_image" section */
	$wp_customize->get_control( 'background_color' )->section = 'background_image';
	
	/* Remove "header_image" section and using our custom header section */
	$wp_customize->remove_section('header_image');
	/* Remove "header_textcolor" control and using our custom header section */
	$wp_customize->remove_control('header_textcolor');
	
}

/**
 * Generate theme customizer options.
 *
 * @since PrimaThemes 2.0
 */
add_action( 'customize_register', 'prima_design_settings_register', 50 );
function prima_design_settings_register( $wp_customize ) {
	if ( !current_theme_supports('prima-design-settings') ) 
		return;

	$design_settings = prima_design_settings();
	
    $default_priority = 140;
	foreach ( $design_settings as $customize ) {
		$default_priority++;
		$defaults = array(
			"name" => "",
			"id" => "",
			"section" => 'colors',
			"database" => PRIMA_DESIGN_SETTINGS,
			"type" => "text",
			"default" => "",
			"options" => array(),
			"priority" => $default_priority,
			"live_preview" => false,
			"css_selector" => "",
			"css_property" => "",
		);
		$customize = wp_parse_args( $customize, $defaults );
		extract( $customize );
		
		if ( $type == 'section' ) {
			$wp_customize->add_section( $id, array(
				'title' => $name,
				'priority' => $priority,
			) );
		}
		else {
			$transport = $live_preview ? 'postMessage' : 'refresh';
			$setting = $database.'['.$id.']';
		}
		switch ( $type ) {
			case 'text':
				$wp_customize->add_setting( $setting, array(
					'default' => $default,
					'type' => 'option',
					'transport' => $transport,
					'sanitize_callback'    => 'prima_design_settings_sanitize_text',
				) );
				$wp_customize->add_control( $setting, array(
					'label' => $name,
					'section' => $section,
					'priority' => $priority,
				) );
			break;
			case 'checkbox':
				$wp_customize->add_setting( $setting, array(
					'default' => $default,
					'type' => 'option',
					'transport' => $transport,
				) );
				$wp_customize->add_control( $setting, array(
					'label' => $name,
					'section' => $section,
					'type' => 'checkbox',
					'priority' => $priority,
				) );
			break;
			case 'select':
				$wp_customize->add_setting( $setting, array(
					'default' => $default,
					'type' => 'option',
					'transport' => $transport,
				) );
				$wp_customize->add_control( $setting, array(
					'label' => $name,
					'section' => $section,
					'type' => 'select',
					'choices' => $options,
					'priority' => $priority,
				) );
			break;
			case 'radio':
				$wp_customize->add_setting( $setting, array(
					'default' => $default,
					'type' => 'option',
					'transport' => $transport,
				) );
				$wp_customize->add_control( $setting, array(
					'label' => $name,
					'section' => $section,
					'type' => 'radio',
					'choices' => $options,
					'priority' => $priority,
				) );
			break;
			case 'color':
				$wp_customize->add_setting( $setting, array(
					'default' => $default,
					'type' => 'option',
					'transport' => $transport,
					'sanitize_callback'    => 'sanitize_hex_color_no_hash',
					'sanitize_js_callback' => 'maybe_hash_hex_color',
				) );
				$wp_customize->add_control( new WP_Customize_Color_Control( $wp_customize, $setting, array(
					'label'   => $name,
					'section' => $section,
					'priority' => $priority,
				) ) );
			break;
			case 'image':
				$wp_customize->add_setting( $setting, array(
					'default' => $default,
					'type' => 'option',
					'transport' => $transport,
				) );
				$wp_customize->add_control( new WP_Customize_Image_Control( $wp_customize, $setting, array(
					'label'   => $name,
					'section' => $section,
					'priority' => $priority,
				) ) );
			break;
		}
	}
}

/**
 * Sanitize text input.
 *
 * @since PrimaThemes 2.0
 */
function prima_design_settings_sanitize_text( $input ) {
    return wp_kses_post( force_balance_tags( $input ) );
}

/**
 * Add action when saving theme customizer.
 *
 * @since PrimaThemes 2.0
 */
add_action( 'customize_save', 'prima_design_settings_customize_save' );
function prima_design_settings_customize_save() {
	update_option( PRIMA_DESIGN_SETTINGS.'_output_expire', 'yes' );
}

/**
 * Generate theme customizer css output.
 *
 * @since PrimaThemes 2.0
 */
add_action( 'admin_head', 'prima_design_settings_generate_output' );
add_action( 'wp_head', 'prima_design_settings_generate_output' );
function prima_design_settings_generate_output() {
	if ( !current_theme_supports('prima-design-settings') ) 
		return;
		
	if ( get_option( PRIMA_DESIGN_SETTINGS.'_output_expire' ) != 'yes' )
		return;
	
	$design_settings = prima_design_settings();
	if ( !$design_settings ) 
		return;
	
	$output = '';
	foreach ( $design_settings as $design_setting ) :
		if ( $design_setting['type'] == 'color' || $design_setting['type'] == 'image' ) {
			$defaults = array(
				"name" => "",
				"id" => "",
				"section" => 'text',
				"database" => PRIMA_DESIGN_SETTINGS,
				"type" => "select",
				"live_preview" => false,
				"css_selector" => "",
				"css_property" => "",
			);
			$design_setting = wp_parse_args( $design_setting, $defaults );
			extract( $design_setting );
			
			if ( $type == 'color' && $css_selector && $css_property ) {
				$value = prima_get_setting($id,PRIMA_DESIGN_SETTINGS);
				if ( $value ) {
					$output .= $css_selector.'{'.$css_property.':#'.$value.'} ';
				}
			}
			elseif ( $type == 'image' && $css_selector && $css_property == 'background-image' ) {
				$value = prima_get_setting($id,PRIMA_DESIGN_SETTINGS);
				if ( $value ) {
					$output .= $css_selector.'{background-image:url("'.$value.'")} ';
				}
			}
		}
	endforeach;
	update_option( PRIMA_DESIGN_SETTINGS.'_output', $output );
	update_option( PRIMA_DESIGN_SETTINGS.'_output_expire', 'no' );
}

/**
 * Echo Design Settings css output.
 *
 * @since PrimaThemes 2.0
 */
add_action( 'prima_custom_styles', 'prima_design_settings_custom_styles' );
function prima_design_settings_custom_styles() {
	if ( !current_theme_supports('prima-design-settings') ) return;
	if ( !is_ssl() ) 
		echo get_option( PRIMA_DESIGN_SETTINGS.'_output' );
	else 
		echo str_replace("http://", "https://", get_option( PRIMA_DESIGN_SETTINGS.'_output' ));
}

/**
 * Generate theme customizer live preview scripts.
 *
 * @since PrimaThemes 2.0
 */
add_action('prima_custom_scripts', 'prima_design_settings_preview');
function prima_design_settings_preview() {
	if ( !current_theme_supports('prima-design-settings') ) 
		return;

	global $wp_customize;
	if ( !isset( $wp_customize ) || !$wp_customize->is_preview() )
		return;
		
	$design_settings = prima_design_settings();
	if ( !$design_settings ) 
		return;
	
?>
	( function( $ ) {
		head = $('head');
<?php
	foreach ( $design_settings as $design_setting ) :
		$defaults = array(
			"name" => "",
			"id" => "",
			"section" => 'text',
			"database" => PRIMA_DESIGN_SETTINGS,
			"type" => "select",
			"live_preview" => false,
			"css_selector" => "",
			"css_property" => "",
		);
		$design_setting = wp_parse_args( $design_setting, $defaults );
		extract( $design_setting );
		
		if ( $type == 'color' && $live_preview && $css_selector && $css_property ) :
		
		?>
		wp.customize('<?php echo $database; ?>[<?php echo $id; ?>]',function( value ) {
			value.bind(function(to) {
				style = $('#design_<?php echo $id; ?>');
				style.remove();
				if ( to ) {
					style = $('<style type="text/css" id="design_<?php echo $id; ?>"><?php echo $css_selector; ?> { <?php echo $css_property; ?>: ' + to + ' }</style>').appendTo( head );
				}
			});
		});
		<?php
		
		elseif ( $type == 'image' && $live_preview && $css_selector && $css_property == 'background-image' ) :
		
		?>
		wp.customize('<?php echo $database; ?>[<?php echo $id; ?>]',function( value ) {
			value.bind(function(to) {
				style = $('#design_<?php echo $id; ?>');
				style.remove();
				if ( to ) {
					style = $('<style type="text/css" id="design_<?php echo $id; ?>"><?php echo $css_selector; ?> { background-image: url("' + to + '") }</style>').appendTo( head );
				}
			});
		});
		<?php
		
		endif;
		
	endforeach;
?>
	} )( jQuery )
<?php
}
