<?php
/**
 * Functions to handle shortcodes
 *
 * WARNING: This file is part of the core PrimaThemes framework.
 * DO NOT edit this file under any circumstances. 
 *
 * @category   PrimaThemes
 * @package    Framework
 * @subpackage Functions
 * @author     PrimaThemes
 * @link       http://www.primathemes.com
 */

if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

/**
 * Add shortcode generator button to visual editor.
 *
 * @since PrimaThemes 2.0
 */
add_action( 'init', 'prima_shortcode_add_button' );
function prima_shortcode_add_button() {
	if ( ! current_user_can('edit_posts') && ! current_user_can('edit_pages') ) return;
	if ( get_user_option('rich_editing') == 'true') :
		add_filter('mce_external_plugins', 'prima_shortcode_add_tinymce_plugin');
		add_filter('mce_buttons', 'prima_shortcode_register_button');
	endif;
}

/**
 * Register shortcode generator button.
 *
 * @since PrimaThemes 2.0
 */
function prima_shortcode_register_button($buttons) {
	array_push($buttons, "prima_shortcodes_general_button");
	return $buttons;
}

/**
 * Register shortcode generator javascript.
 *
 * @since PrimaThemes 2.0
 */
function prima_shortcode_add_tinymce_plugin($plugin_array) {
	global $prima;
	$plugin_array['PrimaShortcodesGeneral'] = PRIMA_ADMIN_URI . '/js/general.sg.js';
	return $plugin_array;
}

/**
 * Update TinyMCE version
 *
 * @since PrimaThemes 2.0
 */
add_filter( 'tiny_mce_version', 'prima_shortcode_refresh_mce' );
function prima_shortcode_refresh_mce($ver) {
	$ver += 3;
	return $ver;
}
